sudo rmmod ut_all
sudo rmmod ut_hw_module
sudo rmmod ut_hw_module2
sudo rmmod ut_hal_module
sudo rmmod ut_hal_module2
sudo rmmod ut_iif
sudo rmmod ut_osal
sudo rmmod ctor_iif
sudo rmmod iif
sudo rmmod ctor_hal_module
sudo rmmod ctor_hal_module2
sudo rmmod ctor_hw_module
sudo rmmod ctor_hw_module2
sudo rmmod ctor_osal
sudo rmmod hal_module
sudo rmmod hw_module
sudo rmmod hal_module2
sudo rmmod hw_module2
sudo rmmod osal_linux_kernel_space
