/////////////////////////////////////////////////////////////////////////////////
//
// File name: Macaca/demo/demo_iif.c
// This demo is the demonstration of how IIF work. In this demo, IIF include the
// feature of supporting single and dual mode. In single mode only module_1's API works.
// In dual mode, all API work (include module_1 and module_2's cooperation APIs).
// To switch mode,it's only need to switch single mode or dual mode's constructor's
// lib dynamically.
//
// ==Single Mode==
// |----------------------------------------------|
// |                  Demo code                   |
// |----------------------------------------------|
//                      |
//                      |
// |----------------------------------------------|
// |                IIF(single mode)              | <-(Generated by IIF single mode constructor)
// |----------------------------------------------|
//         |
//         |
// |------------------|
// |   Module_1       |
// |------------------|
//
//
// ==Dual Mode==
// |----------------------------------------------|
// |                  Demo code                   |
// |----------------------------------------------|
//                      |
//                      |
// |----------------------------------------------|
// |                 IIF(dual mode)               | <-(Generated by IIF dual mode constructor)
// |----------------------------------------------|
//         |                       |
//         |                       |
// |------------------|     |---------------|
// |   Module_1       |     |   Module_2    |
// |------------------|     |---------------|


/////////////////////////////////////////////////////////////////////////////////

#include <iif_pub.h>
#include <ctor_iif_pub.h>
#include <ctor_osal_pub.h>

int main(){

  IifHandle   *iif_handle;
  OsalHandle  *osal_handle;

  CtorOsalCreateHandle(&osal_handle);
  CtorIifCreateHandle(&iif_handle);


  //------------ dual mode's APIs ------------------//
  if(iif_handle->IifDualInit(iif_handle->fd))
    osal_handle->OsalPrint("API not supported\n");
  if(iif_handle->IifDualMethod1(iif_handle->fd))
    osal_handle->OsalPrint("API not supported\n");
  if(iif_handle->IifDualDeinit(iif_handle->fd))
    osal_handle->OsalPrint("API not supported\n");

  //------------ single mode's APIs ------------------//
  if(iif_handle->IifInit(iif_handle->fd))
    osal_handle->OsalPrint("API not supported\n");
  if(iif_handle->IifMethod1(iif_handle->fd))
    osal_handle->OsalPrint("API not supported\n");
  if(iif_handle->IifDeinit(iif_handle->fd))
    osal_handle->OsalPrint("API not supported\n");


  CtorIifDestroyHandle(iif_handle);
  CtorOsalDestroyHandle(osal_handle);

  return 0;
}
